# docker-compose.yml für Coolify
version: '3.8'

services:
  chatterbox-tts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatterbox-tts-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - chatterbox_models:/root/.cache/huggingface
      - ./voices:/app/voices
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  chatterbox_models:
    driver: local